# Generated by Django 4.1 on 2022-08-06 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Выберите изображение для загрузки', upload_to='posts/', verbose_name='Изображение'),
        ),
    ]
