# Generated by Django 4.1 on 2022-08-07 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_comment_pub_date_post_created_alter_comment_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-pub_date',), 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='created',
        ),
        migrations.RemoveField(
            model_name='post',
            name='created',
        ),
    ]
